CREATE TABLE user
(
  id VARCHAR(255) NOT NULL,
  name TEXT NOT NULL,
  avatarUrl TEXT DEFAULT NULL,
  passwordHash VARCHAR(40) DEFAULT NULL,
  verifiedEmail BOOLEAN DEFAULT FALSE,
  verificationCode VARCHAR(40) DEFAULT NULL,
  isAdmin BOOLEAN DEFAULT FALSE,

  subscribeToAll BOOLEAN NOT NULL DEFAULT FALSE,
  subscribeToAllNewIdeas BOOLEAN NOT NULL DEFAULT FALSE,
  subscribeToUpdatesInMyIdeas BOOLEAN NOT NULL DEFAULT TRUE,
  subscribeToUpdatesInIdeasWatching BOOLEAN NOT NULL DEFAULT TRUE,
  subscribeToCommentsOnMyIdeas BOOLEAN NOT NULL DEFAULT TRUE,
  subscribeToCommentsOnIdeasWatching BOOLEAN NOT NULL DEFAULT TRUE,
  subscribeToReplyComments BOOLEAN NOT NULL DEFAULT TRUE,
  subscribeToMentionComments BOOLEAN NOT NULL DEFAULT TRUE,
  subscribeToVotesInMyIdeas BOOLEAN NOT NULL DEFAULT TRUE,
  subscribeToWatchesInMyIdeas BOOLEAN NOT NULL DEFAULT TRUE,
  subscribeToUnwatchesInMyIdeas BOOLEAN NOT NULL DEFAULT FALSE,

  PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE log
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  createdAt BIGINT UNSIGNED NOT NULL,
  requestId BIGINT UNSIGNED NOT NULL,
  requestUri TEXT NOT NULL,
  requestParams JSON NOT NULL,
  userId VARCHAR(255) DEFAULT NULL,
  type VARCHAR(255) NOT NULL,
  data JSON NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE ideastatus
(
  id BIGINT NOT NULL,
  summary TEXT NOT NULL,
  description TEXT NOT NULL,
  referenceId VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (referenceId)
) ENGINE=InnoDB;

CREATE TABLE idea
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  summary TEXT NOT NULL,
  description TEXT NOT NULL,
  createdAt BIGINT UNSIGNED NOT NULL,
  updatedAt BIGINT UNSIGNED NOT NULL,
  userId VARCHAR(255) DEFAULT NULL,
  referenceId VARCHAR(255) DEFAULT NULL,
  statusId BIGINT NOT NULL,
  priority DOUBLE DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (referenceId),
  KEY (userId),
  KEY (statusId),
  FOREIGN KEY (userId) REFERENCES user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (statusId) REFERENCES ideastatus(id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE ideacomment
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ideaId BIGINT UNSIGNED NOT NULL,
  parentId BIGINT UNSIGNED DEFAULT NULL,
  userId VARCHAR(255) DEFAULT NULL,
  createdAt BIGINT UNSIGNED NOT NULL,
  updatedAt BIGINT UNSIGNED NOT NULL,
  message TEXT NOT NULL,
  PRIMARY KEY (id),
  KEY (ideaId),
  KEY (userId),
  KEY (parentId),
  FOREIGN KEY (ideaId) REFERENCES idea(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (parentId) REFERENCES ideacomment(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE ideacommentmention
(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ideaCommentId BIGINT UNSIGNED NOT NULL,
    userId VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY (ideaCommentId, userId),
    KEY (userId),
    FOREIGN KEY (ideaCommentId) REFERENCES ideacomment(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE category
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  summary TEXT NOT NULL,
  description TEXT NOT NULL,
  parentId BIGINT UNSIGNED DEFAULT NULL,
  referenceId VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (referenceId),
  KEY (parentId),
  FOREIGN KEY (parentId) REFERENCES category(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE ideacategory
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ideaId BIGINT UNSIGNED NOT NULL,
  categoryId BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (ideaId, categoryId),
  KEY (categoryId),
  FOREIGN KEY (categoryId) REFERENCES category(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ideaId) REFERENCES idea(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE tag
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  summary TEXT NOT NULL,
  description TEXT NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE ideatag
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ideaId BIGINT UNSIGNED NOT NULL,
  tagId BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (ideaId, tagId),
  KEY (tagId),
  FOREIGN KEY (ideaId) REFERENCES idea(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (tagId) REFERENCES tag(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE relation
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  oppositeId BIGINT UNSIGNED DEFAULT NULL,
  isDirect BOOLEAN NOT NULL DEFAULT '1',
  summary TEXT NOT NULL,
  description TEXT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (oppositeId),
  FOREIGN KEY (oppositeId) REFERENCES relation(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE idearelation
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  relationId BIGINT UNSIGNED NOT NULL,
  ideaId BIGINT UNSIGNED NOT NULL,
  dstIdeaId BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (ideaId, dstIdeaId, relationId),
  KEY (relationId),
  KEY (dstIdeaId),
  FOREIGN KEY (relationId) REFERENCES relation(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ideaId) REFERENCES idea(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (dstIdeaId) REFERENCES idea(id) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE ideavote
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ideaId BIGINT UNSIGNED NOT NULL,
  userId VARCHAR(255) NOT NULL,
  isPositive BOOLEAN NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (ideaId, userId),
  KEY (userId),
  FOREIGN KEY (ideaId) REFERENCES idea(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;


CREATE TABLE categorysubscription
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  userId VARCHAR(255) NOT NULL,
  categoryId BIGINT UNSIGNED NOT NULL,
  included BOOLEAN DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (userId, categoryId),
  KEY (categoryId),
  FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (categoryId) REFERENCES category(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE tagsubscription
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  userId VARCHAR(255) NOT NULL,
  tagId BIGINT UNSIGNED NOT NULL,
  included BOOLEAN NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (userId, tagId),
  KEY (tagId),
  FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (tagId) REFERENCES tag(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE usersubscription
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  userId VARCHAR(255) NOT NULL,
  dstUserId VARCHAR(255) NOT NULL,
  included BOOLEAN NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (userId, dstUserId),
  KEY (dstUserId),
  FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (dstUserId) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE ideasubscription
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  userId VARCHAR(255) NOT NULL,
  ideaId BIGINT UNSIGNED NOT NULL,
  included BOOLEAN NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (userId, ideaId),
  KEY (ideaId),
  FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ideaId) REFERENCES idea(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;


CREATE VIEW idearelationfull AS
SELECT id, relationId, ideaId, dstIdeaId
FROM idearelation
UNION
SELECT ir.id, r.oppositeId, ir.dstIdeaId, ir.ideaId
FROM idearelation ir
INNER JOIN relation r ON r.id = ir.relationId;
